import { useState, useEffect } from 'react';
import { useParams, useNavigate, Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Navbar } from '@/components/Navbar';
import { useAppStore } from '@/store/useAppStore';
import { toast } from 'sonner';
import { 
  ArrowLeft, 
  Download, 
  Clock, 
  DollarSign, 
  AlertTriangle,
  Edit2,
  Check,
  X,
  FileText
} from 'lucide-react';
import { Feature } from '@/types';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export default function ProjectDetail() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const { isAuthenticated, getProject, updateProject } = useAppStore();
  const [project, setProject] = useState(getProject(id || ''));
  const [editingFeature, setEditingFeature] = useState<string | null>(null);
  const [editValues, setEditValues] = useState<Partial<Feature>>({});

  useEffect(() => {
    if (!isAuthenticated) {
      navigate('/login');
      return;
    }
    
    const p = getProject(id || '');
    if (!p) {
      navigate('/dashboard');
      toast.error('Project not found');
      return;
    }
    setProject(p);
  }, [id, isAuthenticated, getProject, navigate]);

  if (!project || !project.estimation) return null;

  const { estimation } = project;

  const startEdit = (feature: Feature) => {
    setEditingFeature(feature.id);
    setEditValues({
      name: feature.name,
      complexity: feature.complexity,
      estimatedHours: feature.estimatedHours,
    });
  };

  const saveEdit = () => {
    if (!editingFeature || !project.estimation) return;

    const updatedFeatures = project.estimation.features.map(f => {
      if (f.id === editingFeature) {
        return { ...f, ...editValues };
      }
      return f;
    });

    const totalHours = updatedFeatures.reduce((acc, f) => acc + f.estimatedHours, 0);
    const riskBuffer = Math.round(totalHours * 0.2);
    const totalWithBuffer = totalHours + riskBuffer;
    const totalCost = totalWithBuffer * estimation.hourlyRate;

    const updatedEstimation = {
      ...project.estimation,
      features: updatedFeatures,
      totalHours,
      riskBuffer,
      totalWithBuffer,
      totalCost,
    };

    updateProject(project.id, { estimation: updatedEstimation });
    setProject({ ...project, estimation: updatedEstimation });
    setEditingFeature(null);
    toast.success('Feature updated');
  };

  const cancelEdit = () => {
    setEditingFeature(null);
    setEditValues({});
  };

  const getComplexityColor = (complexity: string) => {
    switch (complexity) {
      case 'Low': return 'complexity-low bg-complexity-low/10';
      case 'Medium': return 'complexity-medium bg-complexity-medium/10';
      case 'High': return 'complexity-high bg-complexity-high/10';
      default: return 'text-muted-foreground bg-muted';
    }
  };

  const exportToPDF = () => {
    const doc = new jsPDF();
    
    // Title
    doc.setFontSize(20);
    doc.text(project.name, 14, 20);
    
    doc.setFontSize(12);
    doc.setTextColor(100);
    doc.text(`Generated by DevEstimate on ${new Date().toLocaleDateString()}`, 14, 28);
    
    // Summary
    doc.setTextColor(0);
    doc.setFontSize(14);
    doc.text('Project Summary', 14, 42);
    
    doc.setFontSize(10);
    doc.text(`Total Hours: ${estimation.totalWithBuffer}h (incl. ${estimation.riskBuffer}h buffer)`, 14, 50);
    doc.text(`Hourly Rate: $${estimation.hourlyRate}/h`, 14, 56);
    doc.text(`Total Cost: $${estimation.totalCost.toLocaleString()}`, 14, 62);

    // Features table
    autoTable(doc, {
      startY: 72,
      head: [['Feature', 'Complexity', 'Hours']],
      body: estimation.features.map(f => [f.name, f.complexity, `${f.estimatedHours}h`]),
      styles: { fontSize: 9 },
      headStyles: { fillColor: [45, 212, 191] },
    });

    // Assumptions
    const finalY = (doc as any).lastAutoTable.finalY + 10;
    doc.setFontSize(14);
    doc.text('Assumptions', 14, finalY);
    
    doc.setFontSize(9);
    estimation.assumptions.forEach((assumption, i) => {
      doc.text(`• ${assumption}`, 14, finalY + 8 + (i * 5));
    });

    doc.save(`${project.name.replace(/\s+/g, '-').toLowerCase()}-estimate.pdf`);
    toast.success('PDF exported successfully');
  };

  const exportToCSV = () => {
    const headers = ['Feature', 'Description', 'Complexity', 'Hours'];
    const rows = estimation.features.map(f => [
      f.name,
      f.description,
      f.complexity,
      f.estimatedHours.toString(),
    ]);

    rows.push(['', '', '', '']);
    rows.push(['Total Hours', '', '', estimation.totalHours.toString()]);
    rows.push(['Risk Buffer', '', '', estimation.riskBuffer.toString()]);
    rows.push(['Total with Buffer', '', '', estimation.totalWithBuffer.toString()]);
    rows.push(['Hourly Rate', '', '', `$${estimation.hourlyRate}`]);
    rows.push(['Total Cost', '', '', `$${estimation.totalCost}`]);

    const csvContent = [headers, ...rows]
      .map(row => row.map(cell => `"${cell}"`).join(','))
      .join('\n');

    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const link = document.createElement('a');
    link.href = URL.createObjectURL(blob);
    link.download = `${project.name.replace(/\s+/g, '-').toLowerCase()}-estimate.csv`;
    link.click();
    toast.success('CSV exported successfully');
  };

  return (
    <div className="min-h-screen bg-background">
      <Navbar />
      
      <main className="container mx-auto px-4 pt-24 pb-12">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
        >
          {/* Header */}
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-8">
            <div>
              <Link to="/dashboard" className="inline-flex items-center gap-1 text-muted-foreground hover:text-foreground mb-2">
                <ArrowLeft className="h-4 w-4" />
                Back to Dashboard
              </Link>
              <h1 className="text-3xl font-bold">{project.name}</h1>
              {project.description && (
                <p className="text-muted-foreground mt-1">{project.description}</p>
              )}
            </div>
            <div className="flex gap-2">
              <Button variant="outline" onClick={exportToCSV}>
                <FileText className="h-4 w-4" />
                CSV
              </Button>
              <Button variant="hero" onClick={exportToPDF}>
                <Download className="h-4 w-4" />
                Export PDF
              </Button>
            </div>
          </div>

          {/* Summary Cards */}
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 mb-8">
            <Card className="glass border-border/50">
              <CardContent className="p-4">
                <div className="flex items-center gap-3">
                  <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10">
                    <Clock className="h-5 w-5 text-primary" />
                  </div>
                  <div>
                    <p className="text-2xl font-bold">{estimation.totalHours}h</p>
                    <p className="text-sm text-muted-foreground">Base Hours</p>
                  </div>
                </div>
              </CardContent>
            </Card>

            <Card className="glass border-border/50">
              <CardContent className="p-4">
                <div className="flex items-center gap-3">
                  <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-complexity-medium/10">
                    <AlertTriangle className="h-5 w-5 text-complexity-medium" />
                  </div>
                  <div>
                    <p className="text-2xl font-bold">+{estimation.riskBuffer}h</p>
                    <p className="text-sm text-muted-foreground">Risk Buffer (20%)</p>
                  </div>
                </div>
              </CardContent>
            </Card>

            <Card className="glass border-border/50">
              <CardContent className="p-4">
                <div className="flex items-center gap-3">
                  <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10">
                    <Clock className="h-5 w-5 text-primary" />
                  </div>
                  <div>
                    <p className="text-2xl font-bold text-primary">{estimation.totalWithBuffer}h</p>
                    <p className="text-sm text-muted-foreground">Total Hours</p>
                  </div>
                </div>
              </CardContent>
            </Card>

            <Card className="glass border-primary/30 border-2">
              <CardContent className="p-4">
                <div className="flex items-center gap-3">
                  <div className="flex h-10 w-10 items-center justify-center rounded-lg gradient-primary">
                    <DollarSign className="h-5 w-5 text-primary-foreground" />
                  </div>
                  <div>
                    <p className="text-2xl font-bold">${estimation.totalCost.toLocaleString()}</p>
                    <p className="text-sm text-muted-foreground">@ ${estimation.hourlyRate}/h</p>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>

          {/* Features Table */}
          <Card className="mb-8">
            <CardHeader>
              <CardTitle>Feature Breakdown</CardTitle>
              <CardDescription>Click on a feature to edit the estimation</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="overflow-x-auto">
                <table className="w-full">
                  <thead>
                    <tr className="border-b border-border">
                      <th className="text-left py-3 px-4 text-sm font-medium text-muted-foreground">Feature</th>
                      <th className="text-left py-3 px-4 text-sm font-medium text-muted-foreground hidden md:table-cell">Description</th>
                      <th className="text-center py-3 px-4 text-sm font-medium text-muted-foreground">Complexity</th>
                      <th className="text-right py-3 px-4 text-sm font-medium text-muted-foreground">Hours</th>
                      <th className="text-right py-3 px-4 text-sm font-medium text-muted-foreground w-20">Actions</th>
                    </tr>
                  </thead>
                  <tbody>
                    {estimation.features.map((feature, index) => (
                      <motion.tr
                        key={feature.id}
                        initial={{ opacity: 0, y: 10 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ delay: index * 0.05 }}
                        className="border-b border-border/50 hover:bg-secondary/30 transition-colors"
                      >
                        <td className="py-3 px-4">
                          {editingFeature === feature.id ? (
                            <Input
                              value={editValues.name || ''}
                              onChange={(e) => setEditValues({ ...editValues, name: e.target.value })}
                              className="h-8"
                            />
                          ) : (
                            <span className="font-medium">{feature.name}</span>
                          )}
                        </td>
                        <td className="py-3 px-4 text-muted-foreground hidden md:table-cell">
                          {feature.description}
                        </td>
                        <td className="py-3 px-4 text-center">
                          {editingFeature === feature.id ? (
                            <select
                              value={editValues.complexity || 'Medium'}
                              onChange={(e) => setEditValues({ ...editValues, complexity: e.target.value as Feature['complexity'] })}
                              className="h-8 rounded-md border border-border bg-secondary/50 px-2 text-sm"
                            >
                              <option value="Low">Low</option>
                              <option value="Medium">Medium</option>
                              <option value="High">High</option>
                            </select>
                          ) : (
                            <span className={`inline-flex px-2 py-1 rounded-full text-xs font-medium ${getComplexityColor(feature.complexity)}`}>
                              {feature.complexity}
                            </span>
                          )}
                        </td>
                        <td className="py-3 px-4 text-right font-medium">
                          {editingFeature === feature.id ? (
                            <Input
                              type="number"
                              value={editValues.estimatedHours || 0}
                              onChange={(e) => setEditValues({ ...editValues, estimatedHours: parseInt(e.target.value) || 0 })}
                              className="h-8 w-20 ml-auto"
                              min="1"
                            />
                          ) : (
                            <span>{feature.estimatedHours}h</span>
                          )}
                        </td>
                        <td className="py-3 px-4 text-right">
                          {editingFeature === feature.id ? (
                            <div className="flex justify-end gap-1">
                              <Button size="icon" variant="ghost" onClick={saveEdit} className="h-8 w-8">
                                <Check className="h-4 w-4 text-complexity-low" />
                              </Button>
                              <Button size="icon" variant="ghost" onClick={cancelEdit} className="h-8 w-8">
                                <X className="h-4 w-4 text-destructive" />
                              </Button>
                            </div>
                          ) : (
                            <Button size="icon" variant="ghost" onClick={() => startEdit(feature)} className="h-8 w-8">
                              <Edit2 className="h-4 w-4" />
                            </Button>
                          )}
                        </td>
                      </motion.tr>
                    ))}
                  </tbody>
                  <tfoot>
                    <tr className="bg-secondary/30">
                      <td colSpan={3} className="py-3 px-4 font-medium text-right">Total</td>
                      <td className="py-3 px-4 text-right font-bold text-primary">{estimation.totalHours}h</td>
                      <td></td>
                    </tr>
                  </tfoot>
                </table>
              </div>
            </CardContent>
          </Card>

          {/* Assumptions */}
          <Card>
            <CardHeader>
              <CardTitle>Assumptions</CardTitle>
              <CardDescription>This estimate is based on the following assumptions</CardDescription>
            </CardHeader>
            <CardContent>
              <ul className="space-y-2">
                {estimation.assumptions.map((assumption, index) => (
                  <li key={index} className="flex items-start gap-2 text-muted-foreground">
                    <span className="text-primary mt-1">•</span>
                    {assumption}
                  </li>
                ))}
              </ul>
            </CardContent>
          </Card>
        </motion.div>
      </main>
    </div>
  );
}
